# Generated by Django 5.2.15 on 2026-06-12 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KIEinstellung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('gemini', 'Google (Gemini)')], max_length=20, verbose_name='Anbieter')),
                ('modell', models.CharField(blank=True, max_length=100, verbose_name='Modell')),
                ('api_key_verschluesselt', models.TextField(blank=True, verbose_name='API-Key (verschlüsselt)')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ki_einstellung', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KI-Einstellung',
                'verbose_name_plural': 'KI-Einstellungen',
            },
        ),
    ]
