# Generated by Django 5.2.14 on 2026-05-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berechnung', '0001_initial'),
        ('szenarien', '0002_faktoreingabe_unsicherheit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaLauf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('angelegt', 'Angelegt'), ('laeuft', 'Läuft'), ('fertig', 'Fertig'), ('fehler', 'Fehler')], default='angelegt', max_length=20, verbose_name='Status')),
                ('fortschritt', models.PositiveSmallIntegerField(default=0, verbose_name='Fortschritt (%)')),
                ('n_simulations', models.PositiveIntegerField(verbose_name='Anzahl Simulationen')),
                ('random_seed', models.PositiveIntegerField(verbose_name='Zufalls-Seed')),
                ('ergebnis', models.JSONField(blank=True, null=True, verbose_name='Ergebnis')),
                ('fehler_text', models.TextField(blank=True, verbose_name='Fehlertext')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('szenarien', models.ManyToManyField(related_name='meta_laeufe', to='szenarien.szenario', verbose_name='Szenarien')),
            ],
            options={
                'verbose_name': 'Meta-Lauf',
                'verbose_name_plural': 'Meta-Läufe',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
