# Generated by Django 5.2.14 on 2026-05-31 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berechnung', '0002_metalauf'),
        ('szenarien', '0009_vergleich'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalauf',
            name='vergleich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laeufe', to='szenarien.vergleich', verbose_name='Vergleich'),
        ),
    ]
