# Generated by Django 5.2.14 on 2026-05-29 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Szenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('n_simulations', models.PositiveIntegerField(default=10000, verbose_name='Anzahl Simulationen')),
                ('random_seed', models.PositiveIntegerField(default=42, verbose_name='Zufalls-Seed')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
            ],
            options={
                'verbose_name': 'Szenario',
                'verbose_name_plural': 'Szenarien',
                'ordering': ['-geaendert_am'],
            },
        ),
        migrations.CreateModel(
            name='FaktorEingabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faktor', models.CharField(choices=[('LEF', 'Schadenshäufigkeit (Loss Event Frequency)'), ('LM', 'Schadenshöhe (Loss Magnitude)')], max_length=10, verbose_name='Faktor')),
                ('verteilung', models.CharField(choices=[('pert', 'PERT (min / wahrscheinlich / max)'), ('normal', 'Normalverteilung (Mittelwert / Streuung)'), ('constant', 'Konstant (fester Wert)')], default='pert', max_length=20, verbose_name='Verteilung')),
                ('params', models.JSONField(default=dict, verbose_name='Parameter')),
                ('szenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faktoren', to='szenarien.szenario', verbose_name='Szenario')),
            ],
            options={
                'verbose_name': 'Faktor-Eingabe',
                'verbose_name_plural': 'Faktor-Eingaben',
                'constraints': [models.UniqueConstraint(fields=('szenario', 'faktor'), name='unique_faktor_pro_szenario')],
            },
        ),
    ]
