# Generated by Django 5.2.14 on 2026-05-29 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktoreingabe',
            name='unsicherheit',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Unsicherheit'),
        ),
    ]
