# Generated by Django 5.2.14 on 2026-05-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0002_faktoreingabe_unsicherheit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktoreingabe',
            name='faktor',
            field=models.CharField(choices=[('LEF', 'Loss Event Frequency (LEF)'), ('TEF', 'Threat Event Frequency (TEF)'), ('CF', 'Contact Frequency (CF)'), ('POA', 'Probability of Action (PoA)'), ('VULN', 'Vulnerability (Vuln)'), ('TC', 'Threat Capability (TC)'), ('CS', 'Control Strength (CS)'), ('LM', 'Loss Magnitude (LM)'), ('PL', 'Primary Loss (PL)'), ('SL', 'Secondary Loss (SL)'), ('SLEF', 'Secondary Loss Event Frequency (SLEF)'), ('SLEM', 'Secondary Loss Event Magnitude (SLEM)')], max_length=10, verbose_name='Faktor'),
        ),
    ]
