# Generated by Django 5.2.14 on 2026-05-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0003_alter_faktoreingabe_faktor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktoreingabe',
            name='verteilung',
            field=models.CharField(choices=[('pert', 'PERT (min / wahrscheinlich / max)'), ('normal', 'Normalverteilung (Mittelwert / Streuung)'), ('constant', 'Konstant (fester Wert)'), ('poisson', 'Poisson (λ Ereignisse pro Jahr)'), ('beta', 'Beta (Mittelwert 0–1)'), ('lognormal', 'Lognormal (Mittelwert)')], default='pert', max_length=20, verbose_name='Verteilung'),
        ),
    ]
