# Generated by Django 5.2.14 on 2026-05-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0004_alter_faktoreingabe_verteilung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angreifertyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Bezeichnung')),
                ('beschreibung', models.CharField(blank=True, max_length=200, verbose_name='Beschreibung')),
                ('low', models.FloatField(verbose_name='Minimum (0–1)')),
                ('mode', models.FloatField(verbose_name='Wahrscheinlich (0–1)')),
                ('high', models.FloatField(verbose_name='Maximum (0–1)')),
                ('begruendung', models.CharField(blank=True, max_length=200, verbose_name='Begründung')),
                ('typisches_szenario', models.CharField(blank=True, max_length=200, verbose_name='Typisches Szenario')),
                ('reihenfolge', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Angreifertyp',
                'verbose_name_plural': 'Angreifertypen',
                'ordering': ['reihenfolge', 'name'],
            },
        ),
    ]
