# Generated by Django 5.2.14 on 2026-05-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0006_seed_angreifertypen'),
    ]

    operations = [
        migrations.AddField(
            model_name='szenario',
            name='risikotoleranz',
            field=models.JSONField(blank=True, null=True, verbose_name='Risikotoleranz'),
        ),
    ]
