# Generated by Django 5.2.14 on 2026-05-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0007_szenario_risikotoleranz'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktoreingabe',
            name='angreifertyp',
            field=models.CharField(blank=True, max_length=120, verbose_name='Angreifertyp'),
        ),
        migrations.AddField(
            model_name='faktoreingabe',
            name='annahmen',
            field=models.TextField(blank=True, verbose_name='Annahmen'),
        ),
    ]
