# Generated by Django 5.2.14 on 2026-05-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0008_faktoreingabe_angreifertyp_faktoreingabe_annahmen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vergleich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('n_simulations', models.PositiveIntegerField(default=10000, verbose_name='Anzahl Simulationen')),
                ('random_seed', models.PositiveIntegerField(default=42, verbose_name='Zufalls-Seed')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('szenarien', models.ManyToManyField(related_name='vergleiche', to='szenarien.szenario', verbose_name='Szenarien')),
            ],
            options={
                'verbose_name': 'Vergleich',
                'verbose_name_plural': 'Vergleiche',
                'ordering': ['-geaendert_am'],
            },
        ),
    ]
