# Generated by Django 5.2.14 on 2026-05-31 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0009_vergleich'),
    ]

    operations = [
        migrations.AddField(
            model_name='vergleich',
            name='referenz_szenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenz_fuer', to='szenarien.szenario', verbose_name='Referenz-Szenario (Risikotoleranz)'),
        ),
    ]
