# Generated by Django 5.2.14 on 2026-06-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0010_vergleich_referenz_szenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('szenarien', models.ManyToManyField(blank=True, related_name='cluster', to='szenarien.szenario', verbose_name='Szenarien')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Cluster',
                'ordering': ['name'],
            },
        ),
    ]
