# Generated by Django 5.2.15 on 2026-09-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0011_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktoreingabe',
            name='quellentext',
            field=models.TextField(blank=True, verbose_name='Quellentext'),
        ),
    ]
