# Generated by Django 5.2.15 on 2026-09-15 15:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0012_faktoreingabe_quellentext'),
    ]

    operations = [
        migrations.AddField(
            model_name='szenario',
            name='lm_modus',
            field=models.CharField(choices=[('klassisch', 'Klassisch (PL/SL direkt)'), ('formen', '6 Forms of Loss')], default='klassisch', max_length=20, verbose_name='LM-Modus'),
        ),
        migrations.CreateModel(
            name='VerlustFormEingabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verteilung', models.CharField(choices=[('pert', 'PERT (min / wahrscheinlich / max)'), ('normal', 'Normalverteilung (Mittelwert / Streuung)'), ('constant', 'Konstant (fester Wert)'), ('poisson', 'Poisson (λ Ereignisse pro Jahr)'), ('beta', 'Beta (Mittelwert 0–1)'), ('lognormal', 'Lognormal (Mittelwert)')], default='pert', max_length=20, verbose_name='Verteilung')),
                ('params', models.JSONField(default=dict, verbose_name='Parameter')),
                ('unsicherheit', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Unsicherheit')),
                ('annahmen', models.TextField(blank=True, verbose_name='Annahmen')),
                ('quellentext', models.TextField(blank=True, verbose_name='Quellentext')),
                ('seite', models.CharField(choices=[('PL', 'Primary Loss'), ('SL', 'Secondary Loss')], max_length=2, verbose_name='Seite')),
                ('form', models.CharField(choices=[('productivity', 'Productivity'), ('response', 'Response'), ('replacement', 'Replacement'), ('competitive_advantage', 'Competitive Advantage'), ('fines_judgements', 'Fines & Judgements'), ('reputation', 'Reputation')], max_length=30, verbose_name='Loss-Form')),
                ('szenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verlustformen', to='szenarien.szenario', verbose_name='Szenario')),
            ],
            options={
                'verbose_name': 'Verlust-Form-Eingabe',
                'verbose_name_plural': 'Verlust-Form-Eingaben',
                'ordering': ['seite', 'form'],
                'constraints': [models.UniqueConstraint(fields=('szenario', 'seite', 'form'), name='unique_form_pro_seite_und_szenario')],
            },
        ),
    ]
