# Generated by Django 5.2.15 on 2026-09-15 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0013_szenario_lm_modus_verlustformeingabe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szenario',
            name='lm_modus',
            field=models.CharField(choices=[('klassisch', 'Klassisch (PL/SL direkt)'), ('formen', '6 Forms of Loss'), ('fair_mam', 'FAIR-MAM-Fragebogen')], default='klassisch', max_length=20, verbose_name='LM-Modus'),
        ),
        migrations.CreateModel(
            name='VerlustMamEingabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verteilung', models.CharField(choices=[('pert', 'PERT (min / wahrscheinlich / max)'), ('normal', 'Normalverteilung (Mittelwert / Streuung)'), ('constant', 'Konstant (fester Wert)'), ('poisson', 'Poisson (λ Ereignisse pro Jahr)'), ('beta', 'Beta (Mittelwert 0–1)'), ('lognormal', 'Lognormal (Mittelwert)')], default='pert', max_length=20, verbose_name='Verteilung')),
                ('params', models.JSONField(default=dict, verbose_name='Parameter')),
                ('unsicherheit', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Unsicherheit')),
                ('annahmen', models.TextField(blank=True, verbose_name='Annahmen')),
                ('quellentext', models.TextField(blank=True, verbose_name='Quellentext')),
                ('kategorie', models.CharField(choices=[('sensitive_pii_response', 'Sensitive PII Event Response and Management'), ('pci_dss_liability', 'PCI-DSS Liability'), ('information_privacy_liability', 'Information Privacy Liability'), ('regulatory_liability', 'Regulatory Liability'), ('future_net_revenue_loss', 'Loss of Estimated Future Net Revenue'), ('proprietary_data_loss_liability', 'Proprietary Data Loss Liability'), ('direct_business_interruption', 'Direct Business Interruption'), ('contingent_business_interruption', 'Contingent Business Interruption'), ('business_interruption_liability', 'Business Interruption Liability'), ('ransom', 'Ransom'), ('network_event_response', 'Network Event Response and Recovery'), ('network_security_liability', 'Network Security Liability'), ('bec_fraud', 'Business Email Compromise (BEC)'), ('funds_transfer_fraud', 'Funds Transfer Fraud'), ('media_event_response', 'Media Event Response'), ('media_liability', 'Media Liability'), ('server_replacement', 'Server Replacement'), ('computer_replacement', 'Computer/Laptop Replacement'), ('legally_mandated_improvements', 'Legally-Mandated Improvements'), ('voluntary_improvements', 'Voluntary Improvements'), ('customer_retention', 'Customer Retention'), ('future_projects', 'Future Projects'), ('market_value', 'Market Value'), ('cyber_insurance', 'Cyber Insurance'), ('cost_of_capital', 'Cost of Capital'), ('employee_churn', 'Employee Churn')], max_length=40, verbose_name='Kostenkategorie')),
                ('szenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mam_kategorien', to='szenarien.szenario', verbose_name='Szenario')),
            ],
            options={
                'verbose_name': 'FAIR-MAM-Eingabe',
                'verbose_name_plural': 'FAIR-MAM-Eingaben',
                'ordering': ['kategorie'],
                'constraints': [models.UniqueConstraint(fields=('szenario', 'kategorie'), name='unique_kategorie_pro_szenario')],
            },
        ),
    ]
