# Generated by Django 5.2.15 on 2026-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0014_alter_szenario_lm_modus_verlustmameingabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='szenario',
            name='aggregations_modus',
            field=models.CharField(choices=[('elementweise', 'Elementweise (Monte-Carlo-Faltung)'), ('kennwerte', 'Kennwerte (Momente addieren, Lognormal-Näherung)')], default='elementweise', max_length=20, verbose_name='Aggregationsmodus'),
        ),
    ]
