# Generated by Django 5.2.15 on 2026-09-16 15:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0015_szenario_aggregations_modus'),
    ]

    operations = [
        migrations.AddField(
            model_name='szenario',
            name='slef_modus',
            field=models.CharField(choices=[('gemeinsam', 'Gemeinsam (ein SLEF-Wert für alle SL-Formen)'), ('je_form', 'Individuell je Form/Kategorie')], default='gemeinsam', max_length=20, verbose_name='SLEF-Modus'),
        ),
        migrations.CreateModel(
            name='VerlustFormSlef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verteilung', models.CharField(choices=[('pert', 'PERT (min / wahrscheinlich / max)'), ('normal', 'Normalverteilung (Mittelwert / Streuung)'), ('constant', 'Konstant (fester Wert)'), ('poisson', 'Poisson (λ Ereignisse pro Jahr)'), ('beta', 'Beta (Mittelwert 0–1)'), ('lognormal', 'Lognormal (Mittelwert)')], default='pert', max_length=20, verbose_name='Verteilung')),
                ('params', models.JSONField(default=dict, verbose_name='Parameter')),
                ('unsicherheit', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Unsicherheit')),
                ('annahmen', models.TextField(blank=True, verbose_name='Annahmen')),
                ('quellentext', models.TextField(blank=True, verbose_name='Quellentext')),
                ('verlustform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slef', to='szenarien.verlustformeingabe', verbose_name='Loss-Form')),
            ],
            options={
                'verbose_name': 'Individuelle SLEF (Loss-Form)',
                'verbose_name_plural': 'Individuelle SLEF (Loss-Formen)',
            },
        ),
        migrations.CreateModel(
            name='VerlustMamSlef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verteilung', models.CharField(choices=[('pert', 'PERT (min / wahrscheinlich / max)'), ('normal', 'Normalverteilung (Mittelwert / Streuung)'), ('constant', 'Konstant (fester Wert)'), ('poisson', 'Poisson (λ Ereignisse pro Jahr)'), ('beta', 'Beta (Mittelwert 0–1)'), ('lognormal', 'Lognormal (Mittelwert)')], default='pert', max_length=20, verbose_name='Verteilung')),
                ('params', models.JSONField(default=dict, verbose_name='Parameter')),
                ('unsicherheit', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Unsicherheit')),
                ('annahmen', models.TextField(blank=True, verbose_name='Annahmen')),
                ('quellentext', models.TextField(blank=True, verbose_name='Quellentext')),
                ('mam_kategorie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slef', to='szenarien.verlustmameingabe', verbose_name='FAIR-MAM-Kategorie')),
            ],
            options={
                'verbose_name': 'Individuelle SLEF (FAIR-MAM)',
                'verbose_name_plural': 'Individuelle SLEF (FAIR-MAM)',
            },
        ),
    ]
