# Generated by Django 5.2.15 on 2026-09-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szenarien', '0016_szenario_slef_modus_verlustformslef_verlustmamslef'),
    ]

    operations = [
        migrations.AddField(
            model_name='szenario',
            name='cia',
            field=models.JSONField(blank=True, default=list, verbose_name='C/I/A'),
        ),
    ]
