# Generated by Django 5.2.14 on 2026-05-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppKonfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_seed', models.PositiveIntegerField(default=42, verbose_name='Standard-Seed')),
                ('seed_global', models.BooleanField(default=False, help_text='Wenn aktiv, gilt der Standard-Seed für alle Szenarien (Eingabe nur lesend).', verbose_name='Seed global erzwingen')),
                ('standard_n_simulations', models.PositiveIntegerField(default=10000, verbose_name='Standard-Anzahl Simulationen')),
                ('n_simulations_global', models.BooleanField(default=False, help_text='Wenn aktiv, gilt die Standard-Anzahl für alle Szenarien (Eingabe nur lesend).', verbose_name='Simulationsanzahl global erzwingen')),
                ('unternehmens_risikotoleranz', models.JSONField(blank=True, help_text='Kontextbasiert, z. B. {"type": "constant", "value": 100000}.', null=True, verbose_name='Unternehmens-Risikotoleranz')),
                ('risikotoleranz_global', models.BooleanField(default=False, help_text='Wenn aktiv, gilt die Unternehmens-Risikotoleranz für alle Szenarien (Eingabe nur lesend).', verbose_name='Risikotoleranz global erzwingen')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
            ],
            options={
                'verbose_name': 'App-Konfiguration',
                'verbose_name_plural': 'App-Konfiguration',
            },
        ),
    ]
