# Generated by Django 5.2.14 on 2026-06-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bereich', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkonfiguration',
            name='waehrung',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'US-Dollar ($)')], default='EUR', help_text='Bestimmt Währungssymbol und Zahlenformat (€ → 1.234,56 · $ → 1,234.56).', max_length=3, verbose_name='Währung'),
        ),
    ]
