# Generated by Django 5.2.14 on 2026-06-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bereich', '0002_appkonfiguration_waehrung'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkonfiguration',
            name='konfidenz_defaults',
            field=models.JSONField(blank=True, help_text='Überschreibt die Standard-Konfidenztabelle (gamma/sigma/range/k). Leer = Vorgabe.', null=True, verbose_name='Konfidenz-Vorschlagswerte'),
        ),
    ]
