# Generated by Django 5.2.15 on 2026-10-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bereich', '0003_appkonfiguration_konfidenz_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkonfiguration',
            name='deepl_api_key_verschluesselt',
            field=models.TextField(blank=True, verbose_name='DeepL-API-Key (verschlüsselt)'),
        ),
    ]
