# Generated by Django 5.2.15 on 2026-07-27 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamSzenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('n_simulations', models.PositiveIntegerField(default=20000, verbose_name='Anzahl Simulationen')),
                ('random_seed', models.PositiveIntegerField(default=42, verbose_name='Zufalls-Seed')),
                ('tef_low', models.FloatField(verbose_name='TEF min (/Jahr)')),
                ('tef_mode', models.FloatField(verbose_name='TEF wahrscheinlich (/Jahr)')),
                ('tef_high', models.FloatField(verbose_name='TEF max (/Jahr)')),
                ('t_containment_low', models.FloatField(verbose_name='Containment min (Tage)')),
                ('t_containment_mode', models.FloatField(verbose_name='Containment wahrscheinlich (Tage)')),
                ('t_containment_high', models.FloatField(verbose_name='Containment max (Tage)')),
                ('t_resilience_low', models.FloatField(verbose_name='Resilience min (Tage)')),
                ('t_resilience_mode', models.FloatField(verbose_name='Resilience wahrscheinlich (Tage)')),
                ('t_resilience_high', models.FloatField(verbose_name='Resilience max (Tage)')),
                ('concurrency_low', models.FloatField(verbose_name='Concurrency min')),
                ('concurrency_mode', models.FloatField(verbose_name='Concurrency wahrscheinlich')),
                ('concurrency_high', models.FloatField(verbose_name='Concurrency max')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
            ],
            options={
                'verbose_name': 'CAM-Szenario',
                'verbose_name_plural': 'CAM-Szenarien',
                'ordering': ['-geaendert_am'],
            },
        ),
        migrations.CreateModel(
            name='CamControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('intended_efficacy_low', models.FloatField(verbose_name='Intended Efficacy min (0–1)')),
                ('intended_efficacy_mode', models.FloatField(verbose_name='Intended Efficacy wahrscheinlich (0–1)')),
                ('intended_efficacy_high', models.FloatField(verbose_name='Intended Efficacy max (0–1)')),
                ('variant_efficacy_low', models.FloatField(verbose_name='Variant Efficacy min (0–1)')),
                ('variant_efficacy_mode', models.FloatField(verbose_name='Variant Efficacy wahrscheinlich (0–1)')),
                ('variant_efficacy_high', models.FloatField(verbose_name='Variant Efficacy max (0–1)')),
                ('variance_frequency_lambda', models.FloatField(verbose_name='Variance Frequency λ (/Jahr, Poisson)')),
                ('variance_frequency_range', models.FloatField(verbose_name='Variance Frequency range (Poisson)')),
                ('variance_duration_low', models.FloatField(verbose_name='Variance Duration min (Tage)')),
                ('variance_duration_mode', models.FloatField(verbose_name='Variance Duration wahrscheinlich (Tage)')),
                ('variance_duration_high', models.FloatField(verbose_name='Variance Duration max (Tage)')),
                ('coverage_low', models.FloatField(verbose_name='Coverage min (0–1)')),
                ('coverage_mode', models.FloatField(verbose_name='Coverage wahrscheinlich (0–1)')),
                ('coverage_high', models.FloatField(verbose_name='Coverage max (0–1)')),
                ('szenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='cam.camszenario', verbose_name='CAM-Szenario')),
            ],
            options={
                'verbose_name': 'CAM-Control',
                'verbose_name_plural': 'CAM-Controls',
            },
        ),
        migrations.CreateModel(
            name='CamStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reihenfolge', models.PositiveSmallIntegerField(verbose_name='Reihenfolge')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('coverage', models.FloatField(verbose_name='Coverage (0–1)')),
                ('visibility', models.FloatField(verbose_name='Visibility (0–1)')),
                ('vis_reliability', models.FloatField(verbose_name='Visibility Reliability (0–1)')),
                ('recognition', models.FloatField(verbose_name='Recognition (0–1)')),
                ('rec_reliability', models.FloatField(verbose_name='Recognition Reliability (0–1)')),
                ('monitoring_cadence', models.FloatField(verbose_name='Monitoring Cadence (Tage)')),
                ('mon_reliability', models.FloatField(verbose_name='Monitoring Reliability (0–1)')),
                ('duration', models.FloatField(verbose_name='Verweildauer (Tage)')),
                ('progression_probability', models.FloatField(verbose_name='Progression Probability (0–1)')),
                ('review_independence', models.FloatField(verbose_name='Review Independence (0–1)')),
                ('outcome_class', models.CharField(choices=[('early', 'Früh (early)'), ('mid', 'Mittel (mid)'), ('late', 'Spät (late)')], max_length=10, verbose_name='Outcome-Klasse bei Entdeckung')),
                ('szenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='cam.camszenario', verbose_name='CAM-Szenario')),
            ],
            options={
                'verbose_name': 'CAM-Stufe',
                'verbose_name_plural': 'CAM-Stufen (Kill-Chain)',
                'ordering': ['reihenfolge'],
                'constraints': [models.UniqueConstraint(fields=('szenario', 'reihenfolge'), name='unique_stufe_pro_szenario')],
            },
        ),
        migrations.CreateModel(
            name='CamVerlustklasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasse', models.CharField(choices=[('early', 'Früh (early)'), ('mid', 'Mittel (mid)'), ('late', 'Spät (late)'), ('full_impact', 'Voller Schaden (full_impact)'), ('attacker_fails', 'Angreifer scheitert (attacker_fails)')], max_length=20, verbose_name='Klasse')),
                ('low', models.FloatField(verbose_name='Verlust min (€)')),
                ('mode', models.FloatField(verbose_name='Verlust wahrscheinlich (€)')),
                ('high', models.FloatField(verbose_name='Verlust max (€)')),
                ('szenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verlustklassen', to='cam.camszenario', verbose_name='CAM-Szenario')),
            ],
            options={
                'verbose_name': 'CAM-Verlustklasse',
                'verbose_name_plural': 'CAM-Verlustklassen',
                'constraints': [models.UniqueConstraint(fields=('szenario', 'klasse'), name='unique_klasse_pro_szenario')],
            },
        ),
    ]
